# SITE CONFIGURATION
title: Underdog's Triumph # your site title
author: Oliver Jensen # You
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ojensen5115.github.io" # the base hostname & protocol for your site, e.g. http://example.com

collections_dir: collections
collections:
  training_options:
    output: true
    permalink: /training/:name
  shop_items:
    output: true
    permalink: /shop/:name

# SEO PLUGIN
social:
  name: Oliver Jensen
  links:
    - https://twitter.com/ojensen5115
    - https://www.facebook.com/ojensen5115
    - https://www.linkedin.com/in/ojensen5115
    - https://plus.google.com/+BenBalter
    - https://github.com/ojensen5115
    - https://keybase.io/ojensen

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'In-Home Training', link: '/training'}
  - {name: 'Shop', link: '/shop'}
  - {name: 'Blog', link: '/blog'}
  - {name: 'Donate', link: '/donate'}

tagline: >
  Spreading positive and force free training to shelters, fosters and the general public

#hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg
hero_img: dogs.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: ojensen5115@gmail.com # email for form submission

twitter_username: ojensen5115 # replace with your_twitter_username or comment to remove link from footer
github_username:  ojensen5115 # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-money
